/* ─────────────────────────────────────────────────────────────────────
   Los 949 municipios de Catalunya (nombre oficial IDESCAT, orden
   natural con el artículo delante). Fuente: dataset abierto
   jorvixsky/geocatalunya. Se usa SOLO para el autocompletado del campo
   «Población» del formulario de captación; el campo admite texto libre,
   así que esta lista es una comodidad, no una restricción.
   Generado — no editar a mano.
   ───────────────────────────────────────────────────────────────────── */

export const MUNICIPIOS_CATALUNYA: readonly string[] = [
  "Abella de la Conca", "Abrera", "Agramunt", "Aguilar de Segarra", "Agullana", "Aiguafreda",
  "Aiguamúrcia", "Aiguaviva", "Aitona", "l'Albagés", "Albanyà", "Albatàrrec",
  "Albesa", "l'Albi", "Albinyana", "l'Albiol", "Albons", "Alcanar",
  "Alcanó", "Alcarràs", "Alcoletge", "Alcover", "l'Aldea", "Aldover",
  "l'Aleixar", "Alella", "Alfara de Carles", "Alfarràs", "Alforja", "Alfés",
  "Algerri", "Alguaire", "Alins", "Alió", "Almacelles", "Almatret",
  "Almenar", "Almoster", "Alp", "Alpens", "Alpicat", "Alt Àneu",
  "Altafulla", "Altres/Diversos", "Alàs i Cerc", "Alòs de Balaguer", "Amer", "l'Ametlla de Mar",
  "l'Ametlla del Vallès", "l'Ampolla", "Amposta", "Anglesola", "Anglès", "Arbeca",
  "Arbolí", "l'Arboç", "Arbúcies", "Arenys de Mar", "Arenys de Munt", "Argelaguer",
  "l'Argentera", "Argentona", "Argençola", "l'Armentera", "Arnes", "Arres",
  "Arsèguel", "Artesa de Lleida", "Artesa de Segre", "Artés", "Ascó", "Aspa",
  "Avinyonet de Puigventós", "Avinyonet del Penedès", "Avinyó", "Avià", "Badalona", "Badia del Vallès",
  "Bagà", "Baix Pallars", "Balaguer", "Balenyà", "Balsareny", "Banyeres del Penedès",
  "Banyoles", "Barbens", "Barberà de la Conca", "Barberà del Vallès", "Barcelona", "Bassella",
  "Batea", "Bausen", "Begues", "Begur", "Belianes", "Bell-lloc d'Urgell",
  "Bellaguarda", "Bellcaire d'Empordà", "Bellcaire d'Urgell", "Bellmunt d'Urgell", "Bellmunt del Priorat", "Bellprat",
  "Bellpuig", "Bellvei", "Bellver de Cerdanya", "Bellvís", "Benavent de Segrià", "Benifallet",
  "Benissanet", "Berga", "Besalú", "Bescanó", "Beuda", "Bigues i Riells del Fai",
  "Biosca", "Biure", "Blancafort", "Blanes", "Boadella i les Escaules", "Bolvir",
  "Bonastre", "Bordils", "Borrassà", "Borredà", "Bossòst", "Bot",
  "Botarell", "Bovera", "Breda", "Brunyola i Sant Martí Sapresa", "Bràfim", "Bàscara",
  "Cabacés", "Cabanabona", "Cabanelles", "Cabanes", "Cabra del Camp", "Cabrera d'Anoia",
  "Cabrera de Mar", "Cabrils", "Cabó", "Cadaqués", "Calaf", "Calafell",
  "Calders", "Caldes d'Estrac", "Caldes de Malavella", "Caldes de Montbui", "Calella", "Calldetenes",
  "Callús", "Calonge de Segarra", "Calonge i Sant Antoni", "Camarasa", "Camarles", "Cambrils",
  "Campdevànol", "Campelles", "Campins", "Campllong", "Camprodon", "Camós",
  "Canejan", "Canet d'Adri", "Canet de Mar", "Canovelles", "Cantallops", "Canyelles",
  "Capafonts", "Capellades", "Capmany", "Capolat", "Capçanes", "Cardedeu",
  "Cardona", "Carme", "Caseres", "Casserres", "Cassà de la Selva", "Castell d'Aro, Platja d'Aro i s'Agaró",
  "Castell de l'Areny", "Castell de Mur", "Castellar de la Ribera", "Castellar de n'Hug", "Castellar del Riu", "Castellar del Vallès",
  "Castellbell i el Vilar", "Castellbisbal", "Castellcir", "Castelldans", "Castelldefels", "Castellet i la Gornal",
  "Castellfollit de la Roca", "Castellfollit de Riubregós", "Castellfollit del Boix", "Castellgalí", "Castellnou de Bages", "Castellnou de Seana",
  "Castellolí", "Castellserà", "Castellterçol", "Castellvell del Camp", "Castellví de la Marca", "Castellví de Rosanes",
  "Castelló d'Empúries", "Castelló de Farfanya", "Cava", "Celrà", "Centelles", "Cercs",
  "Cerdanyola del Vallès", "Cervelló", "Cervera", "Cervià de les Garrigues", "Cervià de Ter", "Cistella",
  "Ciutadilla", "Clariana de Cardener", "Colera", "Coll de Nargó", "Collbató", "Colldejou",
  "Collsuspina", "Colomers", "Conca de Dalt", "Conesa", "Constantí", "Copons",
  "Corbera d'Ebre", "Corbera de Llobregat", "Corbins", "Cornellà de Llobregat", "Cornellà del Terri", "Cornudella de Montsant",
  "Corçà", "Creixell", "Crespià", "Cruïlles, Monells i Sant Sadurní de l'Heura", "Cubelles", "Cubells",
  "Cunit", "Cànoves i Samalús", "Darnius", "Das", "Deltebre", "Dosrius",
  "Duesaigües", "el Bruc", "el Brull", "el Catllar", "el Cogul", "el Far d'Empordà",
  "el Lloar", "el Masnou", "el Masroig", "el Milà", "el Molar", "el Montmell",
  "el Morell", "el Palau d'Anglesola", "el Papiol", "el Perelló", "el Pinell de Brai", "el Pla de Santa Maria",
  "el Pla del Penedès", "el Poal", "el Pont d'Armentera", "el Pont de Bar", "el Pont de Suert", "el Pont de Vilomara i Rocafort",
  "el Port de la Selva", "el Prat de Llobregat", "el Rourell", "el Soleràs", "el Vendrell", "el Vilosell",
  "els Alamús", "els Garidells", "els Guiamets", "els Hostalets de Pierola", "els Omellons", "els Omells de na Gaia",
  "els Pallaresos", "els Plans de Sió", "els Prats de Rei", "els Torms", "Es Bòrdes", "l'Escala",
  "Esparreguera", "Espinelves", "l'Espluga Calba", "l'Espluga de Francolí", "Esplugues de Llobregat", "Espolla",
  "Esponellà", "Espot", "l'Espunyola", "l'Esquirol", "Estamariu", "l'Estany",
  "Estaràs", "Esterri d'Àneu", "Esterri de Cardós", "Falset", "Farrera", "Figaró-Montmany",
  "Figueres", "Figuerola del Camp", "Flaçà", "Flix", "Fogars de la Selva", "Fogars de Montclús",
  "Foixà", "Folgueroles", "Fondarella", "Fonollosa", "Font-rubí", "Fontanals de Cerdanya",
  "Fontanilles", "Fontcoberta", "Foradada", "Forallac", "Fornells de la Selva", "Fortià",
  "Forès", "Freginals", "Fulleda", "Fígols", "Fígols i Alinyà", "Gaià",
  "Gallifa", "Gandesa", "Garcia", "Garrigoles", "Garriguella", "Garrigàs",
  "Gavet de la Conca", "Gavà", "Gelida", "Ger", "Gimenells i el Pla de la Font", "Ginestar",
  "Girona", "Gironella", "Gisclareny", "Godall", "Golmés", "Gombrèn",
  "Granera", "Granollers", "Granyanella", "Granyena de les Garrigues", "Granyena de Segarra", "Gratallops",
  "Gualba", "Gualta", "Guardiola de Berguedà", "Guils de Cerdanya", "Guimerà", "Guissona",
  "Guixers", "Gurb", "Gósol", "Horta de Sant Joan", "l'Hospitalet de Llobregat", "Hostalric",
  "Igualada", "Isona i Conca Dellà", "Isòvol", "Ivars d'Urgell", "Ivars de Noguera", "Ivorra",
  "Jafre", "Jorba", "Josa i Tuixén", "Juià", "Juncosa", "Juneda",
  "la Baronia de Rialb", "la Bisbal d'Empordà", "la Bisbal de Falset", "la Bisbal del Penedès", "la Canonja", "la Cellera de Ter",
  "la Coma i la Pedra", "la Fatarella", "la Febró", "la Figuera", "la Floresta", "la Fuliola",
  "la Galera", "la Garriga", "la Granada", "la Granadella", "la Granja d'Escarp", "la Guingueta d'Àneu",
  "la Jonquera", "la Llacuna", "la Llagosta", "la Masó", "la Molsosa", "la Morera de Montsant",
  "la Nou de Berguedà", "la Nou de Gaià", "la Palma d'Ebre", "la Palma de Cervelló", "la Pera", "la Pobla de Claramunt",
  "la Pobla de Cérvoles", "la Pobla de Lillet", "la Pobla de Mafumet", "la Pobla de Massaluca", "la Pobla de Montornès", "la Pobla de Segur",
  "la Portella", "la Quar", "la Riba", "la Riera de Gaià", "la Roca del Vallès", "la Ràpita",
  "la Secuita", "la Selva de Mar", "la Selva del Camp", "la Sentiu de Sió", "la Seu d'Urgell", "la Sénia",
  "la Tallada d'Empordà", "la Torre de Cabdella", "la Torre de Claramunt", "la Torre de l'Espanyol", "la Torre de Fontaubella", "la Vajol",
  "la Vall d'en Bas", "la Vall de Bianya", "la Vall de Boí", "la Vansa i Fórnols", "la Vilella Alta", "la Vilella Baixa",
  "Les", "les Avellanes i Santa Linya", "les Borges Blanques", "les Borges del Camp", "les Cabanyes", "les Franqueses del Vallès",
  "les Llosses", "les Masies de Roda", "les Masies de Voltregà", "les Oluges", "les Piles", "les Planes d'Hostoles",
  "les Preses", "les Valls d'Aguilar", "les Valls de Valira", "Linyola", "Lladorre", "Lladurs",
  "Lladó", "Llagostera", "Llambilles", "Llanars", "Llançà", "Llardecans",
  "Llavorsí", "Lleida", "Llers", "Lles de Cerdanya", "Llimiana", "Llinars del Vallès",
  "Lliçà d'Amunt", "Lliçà de Vall", "Llobera", "Llorac", "Llorenç del Penedès", "Lloret de Mar",
  "Lluçà", "Llívia", "Madremanya", "Maials", "Maià de Montcal", "Maldà",
  "Malgrat de Mar", "Malla", "Manlleu", "Manresa", "Margalef", "Marganell",
  "Martorell", "Martorelles", "Marçà", "Mas de Barberans", "Masarac", "Masdenverge",
  "Masllorenç", "Maspujols", "Masquefa", "Massalcoreig", "Massanes", "Massoteres",
  "Matadepera", "Mataró", "Maçanet de Cabrenys", "Maçanet de la Selva", "Mediona", "Menàrguens",
  "Meranges", "Mieres", "Miralcamp", "Miravet", "Moià", "Molins de Rei",
  "Mollerussa", "Mollet de Peralada", "Mollet del Vallès", "Molló", "Monistrol de Calders", "Monistrol de Montserrat",
  "Mont-ral", "Mont-ras", "Mont-roig del Camp", "Montagut i Oix", "Montblanc", "Montbrió del Camp",
  "Montcada i Reixac", "Montclar", "Montellà i Martinet", "Montesquiu", "Montferrer i Castellbò", "Montferri",
  "Montgai", "Montgat", "Montmajor", "Montmaneu", "Montmeló", "Montoliu de Lleida",
  "Montoliu de Segarra", "Montornès de Segarra", "Montornès del Vallès", "Montseny", "Muntanyola", "Mura",
  "Móra d'Ebre", "Móra la Nova", "Nalec", "Naut Aran", "Navarcles", "Navata",
  "Navàs", "Navès", "No consta", "Nulles", "Odèn", "Ogassa",
  "Olesa de Bonesvalls", "Olesa de Montserrat", "Oliana", "Oliola", "Olius", "Olivella",
  "Olost", "Olot", "Olvan", "Olèrdola", "Ordis", "Organyà",
  "Oristà", "Orpí", "Orís", "Os de Balaguer", "Osor", "Ossó de Sió",
  "Pacs del Penedès", "Palafolls", "Palafrugell", "Palamós", "Palau de Santa Eulàlia", "Palau-sator",
  "Palau-saverdera", "Palau-solità i Plegamans", "Pallejà", "Palol de Revardit", "Pals", "Pardines",
  "Parets del Vallès", "Parlavà", "Passanant i Belltall", "Pau", "Paüls", "Pedret i Marzà",
  "Penelles", "Perafita", "Perafort", "Peralada", "Peramola", "Piera",
  "Pineda de Mar", "Pinell de Solsonès", "Pinós", "Pira", "Planoles", "Poboleda",
  "Polinyà", "Pont de Molins", "Pontils", "Pontons", "Ponts", "Pontós",
  "Porqueres", "Porrera", "Portbou", "Pradell de la Teixeta", "Prades", "Prat de Comte",
  "Pratdip", "Prats de Lluçanès", "Prats i Sansor", "Preixana", "Preixens", "Premià de Dalt",
  "Premià de Mar", "Prullans", "Puig-reig", "Puigcerdà", "Puigdàlber", "Puiggròs",
  "Puigpelat", "Puigverd d'Agramunt", "Puigverd de Lleida", "Pujalt", "Quart", "Queralbs",
  "Querol", "Rabós", "Rajadell", "Rasquera", "Regencós", "Rellinars",
  "Renau", "Reus", "Rialp", "Riba-roja d'Ebre", "Ribera d'Ondara", "Ribera d'Urgellet",
  "Ribes de Freser", "Riells i Viabrea", "Riner", "Ripoll", "Ripollet", "Riu de Cerdanya",
  "Riudarenes", "Riudaura", "Riudecanyes", "Riudecols", "Riudellots de la Selva", "Riudoms",
  "Riumors", "Rocafort de Queralt", "Roda de Berà", "Roda de Ter", "Rodonyà", "Roquetes",
  "Roses", "Rosselló", "Rubió", "Rubí", "Rupit i Pruit", "Rupià",
  "Sabadell", "Sagàs", "Saldes", "Sales de Llierca", "Sallent", "Salomó",
  "Salou", "Salt", "Salàs de Pallars", "Sanaüja", "Sant Adrià de Besòs", "Sant Agustí de Lluçanès",
  "Sant Andreu de la Barca", "Sant Andreu de Llavaneres", "Sant Andreu Salou", "Sant Aniol de Finestres", "Sant Antoni de Vilamajor", "Sant Bartomeu del Grau",
  "Sant Boi de Llobregat", "Sant Boi de Lluçanès", "Sant Cebrià de Vallalta", "Sant Celoni", "Sant Climent de Llobregat", "Sant Climent Sescebes",
  "Sant Cugat del Vallès", "Sant Cugat Sesgarrigues", "Sant Esteve de la Sarga", "Sant Esteve de Palautordera", "Sant Esteve Sesrovires", "Sant Feliu de Buixalleu",
  "Sant Feliu de Codines", "Sant Feliu de Guíxols", "Sant Feliu de Llobregat", "Sant Feliu de Pallerols", "Sant Feliu Sasserra", "Sant Ferriol",
  "Sant Fost de Campsentelles", "Sant Fruitós de Bages", "Sant Gregori", "Sant Guim de Freixenet", "Sant Guim de la Plana", "Sant Hilari Sacalm",
  "Sant Hipòlit de Voltregà", "Sant Iscle de Vallalta", "Sant Jaume d'Enveja", "Sant Jaume de Frontanyà", "Sant Jaume de Llierca", "Sant Jaume dels Domenys",
  "Sant Joan de les Abadesses", "Sant Joan de Mollet", "Sant Joan de Vilatorrada", "Sant Joan Despí", "Sant Joan les Fonts", "Sant Jordi Desvalls",
  "Sant Julià de Cerdanyola", "Sant Julià de Ramis", "Sant Julià de Vilatorta", "Sant Julià del Llor i Bonmatí", "Sant Just Desvern", "Sant Llorenç d'Hortons",
  "Sant Llorenç de la Muga", "Sant Llorenç de Morunys", "Sant Llorenç Savall", "Sant Martí d'Albars", "Sant Martí de Centelles", "Sant Martí de Llémena",
  "Sant Martí de Riucorb", "Sant Martí de Tous", "Sant Martí Sarroca", "Sant Martí Sesgueioles", "Sant Martí Vell", "Sant Mateu de Bages",
  "Sant Miquel de Campmajor", "Sant Miquel de Fluvià", "Sant Mori", "Sant Pau de Segúries", "Sant Pere de Ribes", "Sant Pere de Riudebitlles",
  "Sant Pere de Torelló", "Sant Pere de Vilamajor", "Sant Pere Pescador", "Sant Pere Sallavinera", "Sant Pol de Mar", "Sant Quintí de Mediona",
  "Sant Quirze de Besora", "Sant Quirze del Vallès", "Sant Quirze Safaja", "Sant Ramon", "Sant Sadurní d'Anoia", "Sant Sadurní d'Osormort",
  "Sant Salvador de Guardiola", "Sant Vicenç de Castellet", "Sant Vicenç de Montalt", "Sant Vicenç de Torelló", "Sant Vicenç dels Horts", "Santa Bàrbara",
  "Santa Cecília de Voltregà", "Santa Coloma de Cervelló", "Santa Coloma de Farners", "Santa Coloma de Gramenet", "Santa Coloma de Queralt", "Santa Cristina d'Aro",
  "Santa Eugènia de Berga", "Santa Eulàlia de Riuprimer", "Santa Eulàlia de Ronçana", "Santa Fe del Penedès", "Santa Llogaia d'Àlguema", "Santa Margarida de Montbui",
  "Santa Margarida i els Monjos", "Santa Maria d'Oló", "Santa Maria de Besora", "Santa Maria de Martorelles", "Santa Maria de Merlès", "Santa Maria de Miralles",
  "Santa Maria de Palautordera", "Santa Oliva", "Santa Pau", "Santa Perpètua de Mogoda", "Santa Susanna", "Santpedor",
  "Sarral", "Sarrià de Ter", "Sarroca de Bellera", "Sarroca de Lleida", "Saus, Camallera i Llampaies", "Savallà del Comtat",
  "Senan", "Senterada", "Sentmenat", "Serinyà", "Serra de Daró", "Seròs",
  "Setcases", "Seva", "Sidamon", "Sils", "Sitges", "Siurana",
  "Sobremunt", "Solivella", "Solsona", "Sora", "Soriguera", "Sort",
  "Soses", "Subirats", "Sudanell", "Sunyer", "Susqueda", "Súria",
  "Tagamanent", "Talamanca", "Talarn", "Talavera", "Taradell", "Tarragona",
  "Tarroja de Segarra", "Tarrés", "Tavertet", "Tavèrnoles", "Teià", "Terrades",
  "Terrassa", "Tiana", "Tiurana", "Tivenys", "Tivissa", "Tona",
  "Tordera", "Torelló", "Tornabous", "Torre-serona", "Torrebesses", "Torredembarra",
  "Torrefarrera", "Torrefeta i Florejacs", "Torregrossa", "Torrelameu", "Torrelavit", "Torrelles de Foix",
  "Torrelles de Llobregat", "Torrent", "Torres de Segre", "Torroella de Fluvià", "Torroella de Montgrí", "Torroja del Priorat",
  "Tortellà", "Tortosa", "Torà", "Toses", "Tossa de Mar", "Tremp",
  "Tàrrega", "Térmens", "Tírvia", "Ullastrell", "Ullastret", "Ulldecona",
  "Ulldemolins", "Ullà", "Ultramort", "Urús", "Vacarisses", "Vall de Cardós",
  "Vall-llobrega", "Vallbona d'Anoia", "Vallbona de les Monges", "Vallcebre", "Vallclara", "Vallfogona de Balaguer",
  "Vallfogona de Ripollès", "Vallfogona de Riucorb", "Vallgorguina", "Vallirana", "Vallmoll", "Vallromanes",
  "Valls", "Vandellòs i l'Hospitalet de l'Infant", "Veciana", "Ventalló", "Verdú", "Verges",
  "Vespella de Gaià", "Vic", "Vidreres", "Vidrà", "Vielha e Mijaran", "Vila-rodona",
  "Vila-sacra", "Vila-sana", "Vila-seca", "Vilabella", "Vilabertran", "Vilablareix",
  "Vilada", "Viladamat", "Viladasens", "Viladecans", "Viladecavalls", "Vilademuls",
  "Viladrau", "Vilafant", "Vilafranca del Penedès", "Vilagrassa", "Vilajuïga", "Vilalba dels Arcs",
  "Vilalba Sasserra", "Vilaller", "Vilallonga de Ter", "Vilallonga del Camp", "Vilamacolum", "Vilamalla",
  "Vilamaniscle", "Vilamòs", "Vilanant", "Vilanova d'Escornalbou", "Vilanova de l'Aguda", "Vilanova de Bellpuig",
  "Vilanova de la Barca", "Vilanova de Meià", "Vilanova de Prades", "Vilanova de Sau", "Vilanova de Segrià", "Vilanova del Camí",
  "Vilanova del Vallès", "Vilanova i la Geltrú", "Vilaplana", "Vilassar de Dalt", "Vilassar de Mar", "Vilaverd",
  "Vilaür", "Vilobí d'Onyar", "Vilobí del Penedès", "Vilopriu", "Vimbodí i Poblet", "Vinaixa",
  "Vinebre", "Vinyols i els Arcs", "Viver i Serrateix", "Xerta", "Àger", "Òdena",
  "Òrrius",
];
