import type { Lang } from "@/lib/i18n";

type PrivacidadContent = {
  title: string;
  updated: string;
  s1h: string; fieldController: string; fieldNif: string; fieldAddress: string; fieldContact: string;
  s2h: string; s2intro: string;
  s2item1: string; s2item2: string; s2item3: string;
  s3h: string;
  s3t1: string; s3d1: string; s3b1: string;
  s3t2: string; s3d2: string; s3b2: string;
  s3t3: string; s3d3: string; s3b3: string;
  s3t4: string; s3d4: string; s3b4: string;
  s4h: string; s4intro: string;
  s4item1: string; s4item2: string; s4item3: string; s4item4: string;
  s5h: string; s5intro: string;
  s5item1: string; s5item2: string; s5item3: string;
  s5outro: string;
  s6h: string; s6intro: string;
  s6r1: string; s6d1: string;
  s6r2: string; s6d2: string;
  s6r3: string; s6d3: string;
  s6r4: string; s6d4: string;
  s6r5: string; s6d5: string;
  s6r6: string; s6d6: string;
  s6outro1: string; s6outro2: string;
  s7h: string; s7p: string;
  s8h: string;
  s8t1: string; s8p1: string; s8link1: string;
  s8t2: string; s8p2: string; s8link2: string; s8p2b: string;
  s8t3: string; s8p3: string; s8link3: string;
  s9h: string; s9p: string; s9cookiesLink: string;
  backLegal: string; backCookies: string; backHome: string;
};

const data: Record<Lang, PrivacidadContent> = {
  es: {
    title: "Política de Privacidad",
    updated: "Última actualización: mayo 2026",
    s1h: "1. Responsable del tratamiento",
    fieldController: "Responsable", fieldNif: "NIF", fieldAddress: "Dirección", fieldContact: "Contacto en materia de privacidad",
    s2h: "2. Datos que recopilamos",
    s2intro: "Podemos recopilar las siguientes categorías de datos personales:",
    s2item1: "Datos de identificación y contacto: nombre, apellidos, dirección de correo electrónico, número de teléfono.",
    s2item2: "Datos proporcionados voluntariamente a través de formularios de contacto o solicitudes de valoración.",
    s2item3: "Datos de navegación: dirección IP, tipo de navegador, páginas visitadas y duración de la visita (a través de cookies analíticas, previo consentimiento).",
    s3h: "3. Finalidades y bases legales del tratamiento",
    s3t1: "Gestión de consultas e información inmobiliaria",
    s3d1: "Atender las solicitudes de información sobre propiedades o servicios recibidas a través del Sitio Web, teléfono o correo electrónico.",
    s3b1: "Base legal: ejecución de medidas precontractuales a petición del interesado (art. 6.1.b RGPD).",
    s3t2: "Prestación del servicio de intermediación inmobiliaria",
    s3d2: "Gestión de la relación contractual derivada del encargo de compraventa, alquiler o valoración de inmuebles.",
    s3b2: "Base legal: ejecución del contrato (art. 6.1.b RGPD).",
    s3t3: "Envío de comunicaciones comerciales",
    s3d3: "Envío de información sobre inmuebles, servicios o novedades del sector, únicamente si el usuario ha prestado su consentimiento expreso.",
    s3b3: "Base legal: consentimiento del interesado (art. 6.1.a RGPD). Puedes retirar tu consentimiento en cualquier momento.",
    s3t4: "Cumplimiento de obligaciones legales",
    s3d4: "Conservación de documentación según los plazos establecidos por la normativa fiscal, mercantil y de prevención del blanqueo de capitales.",
    s3b4: "Base legal: cumplimiento de una obligación legal (art. 6.1.c RGPD).",
    s4h: "4. Plazos de conservación",
    s4intro: "Los datos se conservarán durante el tiempo necesario para la prestación del servicio y, posteriormente, durante los plazos de prescripción legal aplicables:",
    s4item1: "Datos contractuales: hasta 6 años (obligaciones mercantiles y fiscales).",
    s4item2: "Datos de prevención de blanqueo de capitales: hasta 10 años.",
    s4item3: "Datos de consultas no formalizadas en contrato: hasta 1 año desde la última comunicación.",
    s4item4: "Datos de comunicaciones comerciales: hasta que se retire el consentimiento.",
    s5h: "5. Cesión de datos a terceros",
    s5intro: "No se cederán datos personales a terceros salvo en los siguientes supuestos:",
    s5item1: "Cuando sea necesario para la prestación del servicio (por ejemplo, a otras agencias colaboradoras o a entidades financieras, con tu consentimiento previo).",
    s5item2: "Cuando exista obligación legal (Administración Tributaria, Fuerzas y Cuerpos de Seguridad del Estado, etc.).",
    s5item3: "A encargados del tratamiento (proveedores de servicios tecnológicos) bajo contrato de encargo de tratamiento y con garantías suficientes: Vercel Inc. (alojamiento web y almacenamiento), Resend (envío de correos) y Google LLC (analítica web, previo consentimiento). Además, solo si has aceptado cookies de marketing, los datos de contacto enviados en formularios (seudonimizados mediante hash SHA-256) se comparten con Meta Platforms para medir la eficacia de la publicidad (Meta Pixel y Conversions API).",
    s5outro: "Algunos de estos proveedores están ubicados en Estados Unidos: esas transferencias internacionales se amparan en el Marco de Privacidad de Datos UE-EE.UU. (Data Privacy Framework) y, en su caso, en cláusulas contractuales tipo aprobadas por la Comisión Europea.",
    s6h: "6. Derechos del interesado",
    s6intro: "En virtud del Reglamento General de Protección de Datos (RGPD) y la Ley Orgánica 3/2018 (LOPDGDD), puedes ejercer los siguientes derechos:",
    s6r1: "Acceso", s6d1: "Conocer qué datos tratamos sobre ti.",
    s6r2: "Rectificación", s6d2: "Corregir datos inexactos o incompletos.",
    s6r3: "Supresión", s6d3: "Solicitar la eliminación de tus datos ('derecho al olvido').",
    s6r4: "Limitación", s6d4: "Restringir el tratamiento en determinados supuestos.",
    s6r5: "Portabilidad", s6d5: "Recibir tus datos en formato estructurado y de uso común.",
    s6r6: "Oposición", s6d6: "Oponerse al tratamiento, incluido el marketing directo.",
    s6outro1: "Para ejercer cualquiera de estos derechos, puedes dirigirte a",
    s6outro2: "adjuntando copia de tu DNI o documento equivalente. Tienes derecho a presentar una reclamación ante la Agencia Española de Protección de Datos",
    s7h: "7. Seguridad",
    s7p: "Se han adoptado las medidas técnicas y organizativas necesarias para garantizar la seguridad de los datos personales y evitar su alteración, pérdida, tratamiento o acceso no autorizado, de conformidad con lo establecido en el RGPD.",
    s8h: "8. Herramientas y servicios de terceros",
    s8t1: "Google Analytics",
    s8p1: "Utilizamos Google Analytics (Google LLC) para analizar el uso del Sitio Web. Esta herramienta solo se activa si el usuario otorga su consentimiento para cookies analíticas. Los datos son anonimizados y no se utilizan para identificar personas. Google LLC actúa como encargado del tratamiento bajo el",
    s8link1: "Marco de Privacidad de Datos UE-EE.UU.",
    s8t2: "Widget de valoración de Idealista",
    s8p2: "La página de valoración integra una herramienta de Idealista.com Networks SL. Al utilizar el formulario de valoración, los datos proporcionados son tratados directamente por Idealista conforme a su",
    s8link2: "Política de Privacidad",
    s8p2b: "El titular no tiene acceso a los datos introducidos en el widget.",
    s8t3: "Google Maps",
    s8p3: "La página de contacto muestra un mapa de Google Maps. Al cargar la página, Google Maps puede instalar cookies propias sujetas a su",
    s8link3: "Política de Privacidad",
    s9h: "9. Cookies",
    s9p: "El Sitio Web utiliza cookies propias y de terceros. Para más información, consulte nuestra",
    s9cookiesLink: "Política de Cookies",
    backLegal: "Aviso legal →", backCookies: "Política de cookies →", backHome: "← Volver al inicio",
  },
  ca: {
    title: "Política de Privacitat",
    updated: "Última actualització: maig 2026",
    s1h: "1. Responsable del tractament",
    fieldController: "Responsable", fieldNif: "NIF", fieldAddress: "Adreça", fieldContact: "Contacte en matèria de privacitat",
    s2h: "2. Dades que recopilem",
    s2intro: "Podem recopilar les següents categories de dades personals:",
    s2item1: "Dades d'identificació i contacte: nom, cognoms, adreça de correu electrònic, número de telèfon.",
    s2item2: "Dades proporcionades voluntàriament a través de formularis de contacte o sol·licituds de valoració.",
    s2item3: "Dades de navegació: adreça IP, tipus de navegador, pàgines visitades i durada de la visita (a través de cookies analítiques, previ consentiment).",
    s3h: "3. Finalitats i bases legals del tractament",
    s3t1: "Gestió de consultes i informació immobiliària",
    s3d1: "Atendre les sol·licituds d'informació sobre propietats o serveis rebudes a través del Lloc Web, telèfon o correu electrònic.",
    s3b1: "Base legal: execució de mesures precontractuals a petició de l'interessat (art. 6.1.b RGPD).",
    s3t2: "Prestació del servei d'intermediació immobiliària",
    s3d2: "Gestió de la relació contractual derivada de l'encàrrec de compravenda, lloguer o valoració d'immobles.",
    s3b2: "Base legal: execució del contracte (art. 6.1.b RGPD).",
    s3t3: "Enviament de comunicacions comercials",
    s3d3: "Enviament d'informació sobre immobles, serveis o novetats del sector, únicament si l'usuari ha prestat el seu consentiment exprés.",
    s3b3: "Base legal: consentiment de l'interessat (art. 6.1.a RGPD). Pots retirar el teu consentiment en qualsevol moment.",
    s3t4: "Compliment d'obligacions legals",
    s3d4: "Conservació de documentació segons els terminis establerts per la normativa fiscal, mercantil i de prevenció del blanqueig de capitals.",
    s3b4: "Base legal: compliment d'una obligació legal (art. 6.1.c RGPD).",
    s4h: "4. Terminis de conservació",
    s4intro: "Les dades es conservaran durant el temps necessari per a la prestació del servei i, posteriorment, durant els terminis de prescripció legal aplicables:",
    s4item1: "Dades contractuals: fins a 6 anys (obligacions mercantils i fiscals).",
    s4item2: "Dades de prevenció del blanqueig de capitals: fins a 10 anys.",
    s4item3: "Dades de consultes no formalitzades en contracte: fins a 1 any des de l'última comunicació.",
    s4item4: "Dades de comunicacions comercials: fins que es retiri el consentiment.",
    s5h: "5. Cessió de dades a tercers",
    s5intro: "No es cediran dades personals a tercers excepte en els supòsits següents:",
    s5item1: "Quan sigui necessari per a la prestació del servei (per exemple, a altres agències col·laboradores o a entitats financeres, amb el teu consentiment previ).",
    s5item2: "Quan existeixi obligació legal (Administració Tributària, Forces i Cossos de Seguretat de l'Estat, etc.).",
    s5item3: "A encarregats del tractament (proveïdors de serveis tecnològics) sota contracte d'encàrrec de tractament i amb garanties suficients: Vercel Inc. (allotjament web i emmagatzematge), Resend (enviament de correus) i Google LLC (analítica web, amb consentiment previ). A més, només si has acceptat galetes de màrqueting, les dades de contacte enviades en formularis (pseudonimitzades mitjançant hash SHA-256) es comparteixen amb Meta Platforms per mesurar l'eficàcia de la publicitat (Meta Pixel i Conversions API).",
    s5outro: "Alguns d'aquests proveïdors estan ubicats als Estats Units: aquestes transferències internacionals s'emparen en el Marc de Privadesa de Dades UE-EUA (Data Privacy Framework) i, si escau, en clàusules contractuals tipus aprovades per la Comissió Europea.",
    s6h: "6. Drets de l'interessat",
    s6intro: "En virtut del Reglament General de Protecció de Dades (RGPD) i la Llei Orgànica 3/2018 (LOPDGDD), pots exercir els drets següents:",
    s6r1: "Accés", s6d1: "Conèixer quines dades tractem sobre tu.",
    s6r2: "Rectificació", s6d2: "Corregir dades inexactes o incompletes.",
    s6r3: "Supressió", s6d3: "Sol·licitar l'eliminació de les teves dades ('dret a l'oblit').",
    s6r4: "Limitació", s6d4: "Restringir el tractament en determinats supòsits.",
    s6r5: "Portabilitat", s6d5: "Rebre les teves dades en format estructurat i d'ús comú.",
    s6r6: "Oposició", s6d6: "Oposar-se al tractament, inclòs el màrqueting directe.",
    s6outro1: "Per exercir qualsevol d'aquests drets, pots adreçar-te a",
    s6outro2: "adjuntant còpia del teu DNI o document equivalent. Tens dret a presentar una reclamació davant l'Agència Espanyola de Protecció de Dades",
    s7h: "7. Seguretat",
    s7p: "S'han adoptat les mesures tècniques i organitzatives necessàries per garantir la seguretat de les dades personals i evitar la seva alteració, pèrdua, tractament o accés no autoritzat, de conformitat amb el que estableix el RGPD.",
    s8h: "8. Eines i serveis de tercers",
    s8t1: "Google Analytics",
    s8p1: "Utilitzem Google Analytics (Google LLC) per analitzar l'ús del Lloc Web. Aquesta eina només s'activa si l'usuari atorga el seu consentiment per a cookies analítiques. Les dades són anonimitzades i no s'utilitzen per identificar persones. Google LLC actua com a encarregat del tractament sota el",
    s8link1: "Marc de Privacitat de Dades UE-EUA",
    s8t2: "Widget de valoració d'Idealista",
    s8p2: "La pàgina de valoració integra una eina d'Idealista.com Networks SL. En utilitzar el formulari de valoració, les dades proporcionades són tractades directament per Idealista d'acord amb la seva",
    s8link2: "Política de Privacitat",
    s8p2b: "El titular no té accés a les dades introduïdes al widget.",
    s8t3: "Google Maps",
    s8p3: "La pàgina de contacte mostra un mapa de Google Maps. En carregar la pàgina, Google Maps pot instal·lar cookies pròpies subjectes a la seva",
    s8link3: "Política de Privacitat",
    s9h: "9. Cookies",
    s9p: "El Lloc Web utilitza cookies pròpies i de tercers. Per a més informació, consulteu la nostra",
    s9cookiesLink: "Política de Cookies",
    backLegal: "Avís legal →", backCookies: "Política de cookies →", backHome: "← Tornar a l'inici",
  },
  en: {
    title: "Privacy Policy",
    updated: "Last updated: May 2026",
    s1h: "1. Data Controller",
    fieldController: "Controller", fieldNif: "Tax ID (NIF)", fieldAddress: "Address", fieldContact: "Privacy contact",
    s2h: "2. Data we collect",
    s2intro: "We may collect the following categories of personal data:",
    s2item1: "Identification and contact data: name, surname, email address, phone number.",
    s2item2: "Data voluntarily provided through contact forms or valuation requests.",
    s2item3: "Browsing data: IP address, browser type, pages visited and visit duration (through analytics cookies, subject to prior consent).",
    s3h: "3. Purposes and legal basis for processing",
    s3t1: "Handling enquiries and property information",
    s3d1: "Responding to requests for information about properties or services received via the Website, phone or email.",
    s3b1: "Legal basis: performance of pre-contractual measures at the request of the data subject (Art. 6.1.b GDPR).",
    s3t2: "Provision of real estate intermediation services",
    s3d2: "Managing the contractual relationship arising from a property sale, rental or valuation mandate.",
    s3b2: "Legal basis: performance of a contract (Art. 6.1.b GDPR).",
    s3t3: "Sending commercial communications",
    s3d3: "Sending information about properties, services or industry news, only where the user has given explicit consent.",
    s3b3: "Legal basis: consent of the data subject (Art. 6.1.a GDPR). You may withdraw consent at any time.",
    s3t4: "Compliance with legal obligations",
    s3d4: "Retaining documentation in accordance with the time limits set by tax, commercial and anti-money-laundering regulations.",
    s3b4: "Legal basis: compliance with a legal obligation (Art. 6.1.c GDPR).",
    s4h: "4. Retention periods",
    s4intro: "Data will be retained for as long as necessary to provide the service and, thereafter, for the applicable statutory limitation periods:",
    s4item1: "Contractual data: up to 6 years (commercial and tax obligations).",
    s4item2: "Anti-money-laundering data: up to 10 years.",
    s4item3: "Data from enquiries not formalised in a contract: up to 1 year from the last communication.",
    s4item4: "Commercial communication data: until consent is withdrawn.",
    s5h: "5. Disclosure of data to third parties",
    s5intro: "Personal data will not be disclosed to third parties except in the following cases:",
    s5item1: "When necessary for the provision of the service (for example, to collaborating agencies or financial institutions, with your prior consent).",
    s5item2: "When required by law (Tax Authority, Security Forces, etc.).",
    s5item3: "To data processors (technology service providers) under a data processing agreement and with adequate safeguards: Vercel Inc. (web hosting and storage), Resend (email delivery) and Google LLC (web analytics, with prior consent). In addition, only if you have accepted marketing cookies, contact details submitted through forms (pseudonymised using SHA-256 hashing) are shared with Meta Platforms to measure advertising effectiveness (Meta Pixel and Conversions API).",
    s5outro: "Some of these providers are located in the United States: those international transfers are covered by the EU-US Data Privacy Framework and, where applicable, by standard contractual clauses approved by the European Commission.",
    s6h: "6. Data subject rights",
    s6intro: "Under the General Data Protection Regulation (GDPR) and Organic Law 3/2018 (LOPDGDD), you may exercise the following rights:",
    s6r1: "Access", s6d1: "Know what data we process about you.",
    s6r2: "Rectification", s6d2: "Correct inaccurate or incomplete data.",
    s6r3: "Erasure", s6d3: "Request the deletion of your data ('right to be forgotten').",
    s6r4: "Restriction", s6d4: "Restrict processing in certain circumstances.",
    s6r5: "Portability", s6d5: "Receive your data in a structured, commonly used format.",
    s6r6: "Objection", s6d6: "Object to processing, including direct marketing.",
    s6outro1: "To exercise any of these rights, please contact us at",
    s6outro2: "enclosing a copy of your ID or equivalent document. You have the right to lodge a complaint with the Spanish Data Protection Agency",
    s7h: "7. Security",
    s7p: "The necessary technical and organisational measures have been implemented to ensure the security of personal data and prevent its alteration, loss, processing or unauthorised access, in accordance with the GDPR.",
    s8h: "8. Third-party tools and services",
    s8t1: "Google Analytics",
    s8p1: "We use Google Analytics (Google LLC) to analyse Website usage. This tool is only activated if the user consents to analytics cookies. Data is anonymised and not used to identify individuals. Google LLC acts as data processor under the",
    s8link1: "EU-US Data Privacy Framework",
    s8t2: "Idealista valuation widget",
    s8p2: "The valuation page integrates a tool provided by Idealista.com Networks SL. When using the valuation form, the data provided is processed directly by Idealista in accordance with its",
    s8link2: "Privacy Policy",
    s8p2b: "The controller has no access to the data entered into the widget.",
    s8t3: "Google Maps",
    s8p3: "The contact page displays a Google Maps map. When the page loads, Google Maps may set its own cookies subject to its",
    s8link3: "Privacy Policy",
    s9h: "9. Cookies",
    s9p: "The Website uses its own and third-party cookies. For more information, please see our",
    s9cookiesLink: "Cookie Policy",
    backLegal: "Legal notice →", backCookies: "Cookie policy →", backHome: "← Back to home",
  },
  fr: {
    title: "Politique de Confidentialité",
    updated: "Dernière mise à jour : mai 2026",
    s1h: "1. Responsable du traitement",
    fieldController: "Responsable", fieldNif: "NIF", fieldAddress: "Adresse", fieldContact: "Contact en matière de confidentialité",
    s2h: "2. Données que nous collectons",
    s2intro: "Nous pouvons collecter les catégories suivantes de données personnelles :",
    s2item1: "Données d'identification et de contact : nom, prénom, adresse électronique, numéro de téléphone.",
    s2item2: "Données fournies volontairement via des formulaires de contact ou des demandes d'estimation.",
    s2item3: "Données de navigation : adresse IP, type de navigateur, pages visitées et durée de la visite (via des cookies analytiques, sous réserve de consentement préalable).",
    s3h: "3. Finalités et bases légales du traitement",
    s3t1: "Gestion des demandes et informations immobilières",
    s3d1: "Traiter les demandes d'information sur les biens ou services reçues via le Site Web, par téléphone ou par e-mail.",
    s3b1: "Base légale : exécution de mesures précontractuelles à la demande de la personne concernée (art. 6.1.b RGPD).",
    s3t2: "Prestation de services d'intermédiation immobilière",
    s3d2: "Gestion de la relation contractuelle découlant du mandat de vente, de location ou d'estimation d'un bien immobilier.",
    s3b2: "Base légale : exécution d'un contrat (art. 6.1.b RGPD).",
    s3t3: "Envoi de communications commerciales",
    s3d3: "Envoi d'informations sur des biens, services ou actualités du secteur, uniquement si l'utilisateur a donné son consentement exprès.",
    s3b3: "Base légale : consentement de la personne concernée (art. 6.1.a RGPD). Vous pouvez retirer votre consentement à tout moment.",
    s3t4: "Respect des obligations légales",
    s3d4: "Conservation de la documentation conformément aux délais fixés par la réglementation fiscale, commerciale et de lutte contre le blanchiment de capitaux.",
    s3b4: "Base légale : respect d'une obligation légale (art. 6.1.c RGPD).",
    s4h: "4. Durées de conservation",
    s4intro: "Les données seront conservées pendant le temps nécessaire à la prestation du service et, ensuite, pendant les délais de prescription légale applicables :",
    s4item1: "Données contractuelles : jusqu'à 6 ans (obligations commerciales et fiscales).",
    s4item2: "Données de lutte contre le blanchiment : jusqu'à 10 ans.",
    s4item3: "Données de demandes non formalisées en contrat : jusqu'à 1 an depuis la dernière communication.",
    s4item4: "Données de communications commerciales : jusqu'au retrait du consentement.",
    s5h: "5. Communication de données à des tiers",
    s5intro: "Les données personnelles ne seront pas communiquées à des tiers, sauf dans les cas suivants :",
    s5item1: "Lorsque cela est nécessaire pour la prestation du service (par exemple, à d'autres agences partenaires ou à des établissements financiers, avec votre consentement préalable).",
    s5item2: "Lorsqu'une obligation légale l'exige (Administration fiscale, Forces de l'ordre, etc.).",
    s5item3: "À des sous-traitants (prestataires de services technologiques) dans le cadre d'un contrat de sous-traitance et avec des garanties suffisantes : Vercel Inc. (hébergement web et stockage), Resend (envoi d'e-mails) et Google LLC (analyse web, avec consentement préalable). De plus, uniquement si vous avez accepté les cookies marketing, les coordonnées envoyées via les formulaires (pseudonymisées par hachage SHA-256) sont partagées avec Meta Platforms pour mesurer l'efficacité de la publicité (Meta Pixel et Conversions API).",
    s5outro: "Certains de ces prestataires sont situés aux États-Unis : ces transferts internationaux sont couverts par le Cadre de Protection des Données UE-États-Unis (Data Privacy Framework) et, le cas échéant, par des clauses contractuelles types approuvées par la Commission européenne.",
    s6h: "6. Droits de la personne concernée",
    s6intro: "En vertu du Règlement Général sur la Protection des Données (RGPD) et de la loi organique 3/2018 (LOPDGDD), vous pouvez exercer les droits suivants :",
    s6r1: "Accès", s6d1: "Savoir quelles données nous traitons vous concernant.",
    s6r2: "Rectification", s6d2: "Corriger des données inexactes ou incomplètes.",
    s6r3: "Effacement", s6d3: "Demander la suppression de vos données ('droit à l'oubli').",
    s6r4: "Limitation", s6d4: "Restreindre le traitement dans certains cas.",
    s6r5: "Portabilité", s6d5: "Recevoir vos données dans un format structuré et couramment utilisé.",
    s6r6: "Opposition", s6d6: "Vous opposer au traitement, y compris au marketing direct.",
    s6outro1: "Pour exercer l'un de ces droits, veuillez nous contacter à",
    s6outro2: "en joignant une copie de votre pièce d'identité. Vous avez le droit d'introduire une réclamation auprès de l'Agence Espagnole de Protection des Données",
    s7h: "7. Sécurité",
    s7p: "Les mesures techniques et organisationnelles nécessaires ont été mises en place pour garantir la sécurité des données personnelles et prévenir leur altération, perte, traitement ou accès non autorisé, conformément au RGPD.",
    s8h: "8. Outils et services tiers",
    s8t1: "Google Analytics",
    s8p1: "Nous utilisons Google Analytics (Google LLC) pour analyser l'utilisation du Site Web. Cet outil n'est activé que si l'utilisateur consent aux cookies analytiques. Les données sont anonymisées et ne sont pas utilisées pour identifier des personnes. Google LLC agit en tant que sous-traitant dans le cadre du",
    s8link1: "Cadre de Protection des Données UE-États-Unis",
    s8t2: "Widget d'estimation Idealista",
    s8p2: "La page d'estimation intègre un outil d'Idealista.com Networks SL. En utilisant le formulaire d'estimation, les données fournies sont traitées directement par Idealista conformément à sa",
    s8link2: "Politique de Confidentialité",
    s8p2b: "Le responsable n'a pas accès aux données saisies dans le widget.",
    s8t3: "Google Maps",
    s8p3: "La page de contact affiche une carte Google Maps. Au chargement de la page, Google Maps peut installer ses propres cookies soumis à sa",
    s8link3: "Politique de Confidentialité",
    s9h: "9. Cookies",
    s9p: "Le Site Web utilise des cookies propres et de tiers. Pour plus d'informations, veuillez consulter notre",
    s9cookiesLink: "Politique de Cookies",
    backLegal: "Mentions légales →", backCookies: "Politique de cookies →", backHome: "← Retour à l'accueil",
  },
};

export function getPrivacidadContent(lang: Lang): PrivacidadContent {
  return data[lang] ?? data.es;
}
