import type { Lang } from "@/lib/i18n";

type CookiesContent = {
  title: string;
  updated: string;
  s1h: string; s1p: string;
  s2h: string; s2intro: string;
  catNecessary: string; catNecessaryDesc: string;
  colCookie: string; colProvider: string; colDuration: string; colPurpose: string;
  colCategory: string; colRetention: string;
  fieldEmail: string;
  idealistaPrivacy: string;
  ownProvider: string; session: string; months12: string;
  rowSession: string; rowConsent: string; rowPhp: string;
  catAnalytics: string; catAnalyticsDesc: string;
  years2: string; hours24: string;
  rowGa: string; rowGaStar: string; rowGid: string;
  moreInfo: string; googlePrivacy: string;
  catThirdParty: string; catThirdPartyDesc: string;
  variable: string; rowMaps: string; rowWidget: string;
  s3h: string;
  s3t1: string; s3d1: string;
  s3t2: string; s3d2: string;
  s3t3: string; s3d3: string;
  s4h: string;
  s4t1: string; s4d1: string;
  s4t2: string; s4d2: string;
  s5h: string;
  s5c1: string; s5p1: string;
  s5c2: string; s5p2: string;
  s5c3: string; s5p3: string;
  s5c4: string; s5p4: string;
  s6h: string; s6p1: string; s6link1: string; s6p2: string;
  s7h: string; s7intro: string;
  s7a: string; s7aDesc1: string; s7aDesc2: string;
  s7b: string; s7bDesc: string;
  s7disclaimer: string; s7note: string;
  s8h: string; s8p: string;
  s9h: string; s9p: string;
  backLegal: string; backPrivacy: string; backHome: string;
};

const data: Record<Lang, CookiesContent> = {
  es: {
    title: "Política de Cookies",
    updated: "Última actualización: mayo 2026",
    s1h: "1. ¿Qué son las cookies?",
    s1p: "Las cookies son pequeños archivos de texto que los sitios web almacenan en el dispositivo del usuario cuando este los visita. Sirven para que el sitio recuerde información sobre la visita: qué páginas se han consultado, qué preferencias se han indicado o si se ha iniciado sesión. Las cookies no pueden ejecutar programas ni transmitir virus; son simplemente ficheros de texto.",
    s2h: "2. ¿Qué cookies utilizamos?",
    s2intro: "A continuación se detallan todas las cookies utilizadas en thevilahome.com, agrupadas por categoría:",
    catNecessary: "Necesarias",
    catNecessaryDesc: "Imprescindibles para el funcionamiento básico del sitio web. No requieren consentimiento previo del usuario.",
    colCookie: "Cookie", colProvider: "Proveedor", colDuration: "Duración", colPurpose: "Finalidad",
    colCategory: "Categoría", colRetention: "Periodo de conservación",
    fieldEmail: "Correo electrónico",
    idealistaPrivacy: "Política de privacidad de Idealista",
    ownProvider: "Propia", session: "Sesión", months12: "12 meses",
    rowSession: "Gestión de sesión del usuario",
    rowConsent: "Guardar las preferencias de cookies del usuario",
    rowPhp: "Funcionamiento técnico del sitio web",
    catAnalytics: "Analíticas",
    catAnalyticsDesc: "Permiten medir el uso del sitio web mediante la recopilación y análisis estadístico del tráfico. Son gestionadas por Google LLC como tercero encargado del tratamiento. Solo se activan si el usuario otorga su consentimiento.",
    years2: "2 años", hours24: "24 horas",
    rowGa: "Distinguir usuarios únicos",
    rowGaStar: "Mantener el estado de sesión de Analytics",
    rowGid: "Distinguir usuarios durante la sesión",
    moreInfo: "Más información:", googlePrivacy: "Política de privacidad de Google",
    catThirdParty: "Servicios de terceros",
    catThirdPartyDesc: "Determinadas páginas incluyen herramientas de terceros: un mapa de Google Maps en /contacto y el widget de valoración de Idealista en /valoracion. Estos servicios pueden instalar sus propias cookies.",
    variable: "Variable",
    rowMaps: "Mostrar mapa interactivo en /contacto",
    rowWidget: "Widget de valoración en /valoracion",
    s3h: "3. ¿Para qué usamos las cookies?",
    s3t1: "Cookies necesarias",
    s3d1: "Garantizan el funcionamiento técnico del sitio web: mantienen la sesión del usuario activa durante la navegación y almacenan sus preferencias sobre el consentimiento de cookies para no volver a solicitárselas en cada visita.",
    s3t2: "Cookies analíticas",
    s3d2: "Permiten obtener estadísticas agregadas sobre el uso del sitio web: páginas visitadas, tiempo de permanencia, origen del tráfico y comportamiento general de los usuarios. Esta información se utiliza exclusivamente para mejorar el rendimiento y los contenidos del sitio.",
    s3t3: "Servicios de terceros",
    s3d3: "Los servicios embebidos de Google Maps e Idealista operan de forma independiente. Las cookies que instalan estos servicios están fuera del control del titular y se rigen exclusivamente por las políticas de privacidad de sus respectivos proveedores.",
    s4h: "4. Base legal del tratamiento",
    s4t1: "Cookies necesarias",
    s4d1: "La base legal es el interés legítimo del responsable y la necesidad para la prestación del servicio, de conformidad con el artículo 6.1.b) del Reglamento (UE) 2016/679 (RGPD). Estas cookies no requieren consentimiento previo del usuario.",
    s4t2: "Cookies analíticas y de servicios de terceros",
    s4d2: "La base legal es el consentimiento del usuario, de conformidad con el artículo 6.1.a) del RGPD y el artículo 22.2 de la Ley 34/2002 (LSSI). El usuario puede retirar su consentimiento en cualquier momento sin que ello afecte a la licitud del tratamiento realizado con anterioridad.",
    s5h: "5. Periodo de conservación",
    s5c1: "Necesarias (sesión)", s5p1: "Se eliminan al cerrar el navegador",
    s5c2: "Necesarias (preferencias)", s5p2: "12 meses desde su creación",
    s5c3: "Analíticas (Google Analytics)", s5p3: "Entre 24 horas y 2 años, según la cookie",
    s5c4: "Servicios de terceros", s5p4: "Variable; véanse las políticas de cada proveedor",
    s6h: "6. Transferencias internacionales de datos",
    s6p1: "Google LLC está establecida en los Estados Unidos de América. Las transferencias de datos personales a Google LLC se amparan en las Cláusulas Contractuales Tipo aprobadas por la Comisión Europea y en el marco del EU-US Data Privacy Framework. Para más información, puede consultar la",
    s6link1: "política de privacidad de Google",
    s6p2: "Idealista.com Networks SL está establecida en España (Unión Europea), por lo que el tratamiento de datos realizado por este proveedor no constituye transferencia internacional de datos.",
    s7h: "7. ¿Cómo gestionar o retirar el consentimiento?",
    s7intro: "El usuario puede gestionar, modificar o retirar su consentimiento en cualquier momento de dos formas:",
    s7a: "a) Panel de gestión de cookies de la web",
    s7aDesc1: "Haciendo clic en el enlace",
    s7aDesc2: "situado en el pie de página, el usuario podrá activar o desactivar cada categoría de cookies en cualquier momento.",
    s7b: "b) Configuración del navegador",
    s7bDesc: "También puede gestionar, bloquear o eliminar las cookies instaladas en su dispositivo a través de la configuración de su navegador:",
    s7disclaimer: "La desactivación de determinadas cookies puede afectar al correcto funcionamiento del sitio web.",
    s7note: "La retirada del consentimiento no afectará a la licitud del tratamiento basado en el consentimiento previo a su retirada.",
    s8h: "8. Actualización de esta política",
    s8p: "El titular se reserva el derecho de actualizar esta Política de Cookies en cualquier momento, por ejemplo para adaptarla a cambios legislativos o a modificaciones en los servicios del sitio web. Se recomienda revisar esta página periódicamente.",
    s9h: "9. Contacto",
    s9p: "Para cualquier consulta relacionada con el uso de cookies en este sitio web, puede dirigirse al responsable del tratamiento:",
    backLegal: "Aviso legal →", backPrivacy: "Política de privacidad →", backHome: "← Volver al inicio",
  },
  ca: {
    title: "Política de Cookies",
    updated: "Última actualització: maig 2026",
    s1h: "1. Què són les cookies?",
    s1p: "Les cookies són petits fitxers de text que els llocs web emmagatzemen al dispositiu de l'usuari quan els visita. Serveixen perquè el lloc recordi informació sobre la visita: quines pàgines s'han consultat, quines preferències s'han indicat o si s'ha iniciat sessió. Les cookies no poden executar programes ni transmetre virus; són simplement fitxers de text.",
    s2h: "2. Quines cookies utilitzem?",
    s2intro: "A continuació es detallen totes les cookies utilitzades a thevilahome.com, agrupades per categoria:",
    catNecessary: "Necessàries",
    catNecessaryDesc: "Imprescindibles per al funcionament bàsic del lloc web. No requereixen consentiment previ de l'usuari.",
    colCookie: "Cookie", colProvider: "Proveïdor", colDuration: "Durada", colPurpose: "Finalitat",
    colCategory: "Categoria", colRetention: "Període de conservació",
    fieldEmail: "Correu electrònic",
    idealistaPrivacy: "Política de privacitat d'Idealista",
    ownProvider: "Pròpia", session: "Sessió", months12: "12 mesos",
    rowSession: "Gestió de sessió de l'usuari",
    rowConsent: "Desar les preferències de cookies de l'usuari",
    rowPhp: "Funcionament tècnic del lloc web",
    catAnalytics: "Analítiques",
    catAnalyticsDesc: "Permeten mesurar l'ús del lloc web mitjançant la recopilació i l'anàlisi estadística del trànsit. Són gestionades per Google LLC com a tercer encarregat del tractament. Només s'activen si l'usuari atorga el seu consentiment.",
    years2: "2 anys", hours24: "24 hores",
    rowGa: "Distingir usuaris únics",
    rowGaStar: "Mantenir l'estat de sessió d'Analytics",
    rowGid: "Distingir usuaris durant la sessió",
    moreInfo: "Més informació:", googlePrivacy: "Política de privacitat de Google",
    catThirdParty: "Serveis de tercers",
    catThirdPartyDesc: "Determinades pàgines inclouen eines de tercers: un mapa de Google Maps a /contacto i el widget de valoració d'Idealista a /valoracion. Aquests serveis poden instal·lar les seves pròpies cookies.",
    variable: "Variable",
    rowMaps: "Mostrar mapa interactiu a /contacto",
    rowWidget: "Widget de valoració a /valoracion",
    s3h: "3. Per a què fem servir les cookies?",
    s3t1: "Cookies necessàries",
    s3d1: "Garanteixen el funcionament tècnic del lloc web: mantenen la sessió de l'usuari activa durant la navegació i emmagatzemen les seves preferències sobre el consentiment de cookies per no tornar a sol·licitar-les en cada visita.",
    s3t2: "Cookies analítiques",
    s3d2: "Permeten obtenir estadístiques agregades sobre l'ús del lloc web: pàgines visitades, temps de permanència, origen del trànsit i comportament general dels usuaris. Aquesta informació s'utilitza exclusivament per millorar el rendiment i els continguts del lloc.",
    s3t3: "Serveis de tercers",
    s3d3: "Els serveis incrustats de Google Maps i Idealista operen de manera independent. Les cookies que instal·len aquests serveis estan fora del control del titular i es regeixen exclusivament per les polítiques de privacitat dels seus respectius proveïdors.",
    s4h: "4. Base legal del tractament",
    s4t1: "Cookies necessàries",
    s4d1: "La base legal és l'interès legítim del responsable i la necessitat per a la prestació del servei, de conformitat amb l'article 6.1.b) del Reglament (UE) 2016/679 (RGPD). Aquestes cookies no requereixen consentiment previ de l'usuari.",
    s4t2: "Cookies analítiques i de serveis de tercers",
    s4d2: "La base legal és el consentiment de l'usuari, de conformitat amb l'article 6.1.a) del RGPD i l'article 22.2 de la Llei 34/2002 (LSSI). L'usuari pot retirar el seu consentiment en qualsevol moment sense que això afecti la licitud del tractament realitzat anteriorment.",
    s5h: "5. Període de conservació",
    s5c1: "Necessàries (sessió)", s5p1: "S'eliminen en tancar el navegador",
    s5c2: "Necessàries (preferències)", s5p2: "12 mesos des de la seva creació",
    s5c3: "Analítiques (Google Analytics)", s5p3: "Entre 24 hores i 2 anys, segons la cookie",
    s5c4: "Serveis de tercers", s5p4: "Variable; consulteu les polítiques de cada proveïdor",
    s6h: "6. Transferències internacionals de dades",
    s6p1: "Google LLC està establerta als Estats Units d'Amèrica. Les transferències de dades personals a Google LLC s'emparen en les Clàusules Contractuals Tipus aprovades per la Comissió Europea i en el marc de l'EU-US Data Privacy Framework. Per a més informació, podeu consultar la",
    s6link1: "política de privacitat de Google",
    s6p2: "Idealista.com Networks SL està establerta a Espanya (Unió Europea), de manera que el tractament de dades realitzat per aquest proveïdor no constitueix transferència internacional de dades.",
    s7h: "7. Com gestionar o retirar el consentiment?",
    s7intro: "L'usuari pot gestionar, modificar o retirar el seu consentiment en qualsevol moment de dues formes:",
    s7a: "a) Panell de gestió de cookies del web",
    s7aDesc1: "Fent clic a l'enllaç",
    s7aDesc2: "situat al peu de pàgina, l'usuari podrà activar o desactivar cada categoria de cookies en qualsevol moment.",
    s7b: "b) Configuració del navegador",
    s7bDesc: "També pot gestionar, bloquejar o eliminar les cookies instal·lades al seu dispositiu a través de la configuració del seu navegador:",
    s7disclaimer: "La desactivació de determinades cookies pot afectar el funcionament correcte del lloc web.",
    s7note: "La retirada del consentiment no afectarà la licitud del tractament basat en el consentiment previ a la seva retirada.",
    s8h: "8. Actualització d'aquesta política",
    s8p: "El titular es reserva el dret d'actualitzar aquesta Política de Cookies en qualsevol moment, per exemple per adaptar-la a canvis legislatius o a modificacions en els serveis del lloc web. Es recomana revisar aquesta pàgina periòdicament.",
    s9h: "9. Contacte",
    s9p: "Per a qualsevol consulta relacionada amb l'ús de cookies en aquest lloc web, podeu adreçar-vos al responsable del tractament:",
    backLegal: "Avís legal →", backPrivacy: "Política de privacitat →", backHome: "← Tornar a l'inici",
  },
  en: {
    title: "Cookie Policy",
    updated: "Last updated: May 2026",
    s1h: "1. What are cookies?",
    s1p: "Cookies are small text files that websites store on a user's device when they visit. They allow the site to remember information about the visit — which pages were viewed, preferences set, or whether the user was logged in. Cookies cannot run programs or transmit viruses; they are simply text files.",
    s2h: "2. Which cookies do we use?",
    s2intro: "Below is a full list of cookies used on thevilahome.com, grouped by category:",
    catNecessary: "Necessary",
    catNecessaryDesc: "Essential for the basic functioning of the website. These do not require prior consent from the user.",
    colCookie: "Cookie", colProvider: "Provider", colDuration: "Duration", colPurpose: "Purpose",
    colCategory: "Category", colRetention: "Retention period",
    fieldEmail: "Email",
    idealistaPrivacy: "Idealista Privacy Policy",
    ownProvider: "Own", session: "Session", months12: "12 months",
    rowSession: "User session management",
    rowConsent: "Store the user's cookie preferences",
    rowPhp: "Technical operation of the website",
    catAnalytics: "Analytics",
    catAnalyticsDesc: "Allow us to measure website usage through statistical collection and analysis of traffic. Managed by Google LLC as a third-party data processor. Only activated if the user consents.",
    years2: "2 years", hours24: "24 hours",
    rowGa: "Distinguish unique users",
    rowGaStar: "Maintain Analytics session state",
    rowGid: "Distinguish users during a session",
    moreInfo: "More information:", googlePrivacy: "Google Privacy Policy",
    catThirdParty: "Third-party services",
    catThirdPartyDesc: "Certain pages embed third-party tools: a Google Maps map on /contacto and the Idealista valuation widget on /valoracion. These services may set their own cookies.",
    variable: "Variable",
    rowMaps: "Display interactive map on /contacto",
    rowWidget: "Valuation widget on /valoracion",
    s3h: "3. What do we use cookies for?",
    s3t1: "Necessary cookies",
    s3d1: "Ensure the technical functioning of the website: they keep the user's session active during browsing and store cookie consent preferences so users are not asked again on each visit.",
    s3t2: "Analytics cookies",
    s3d2: "Allow us to gather aggregated statistics on website usage: pages visited, time on site, traffic sources and general user behaviour. This information is used solely to improve site performance and content.",
    s3t3: "Third-party services",
    s3d3: "The embedded Google Maps and Idealista services operate independently. Cookies set by these services are outside the controller's control and are governed exclusively by each provider's privacy policy.",
    s4h: "4. Legal basis for processing",
    s4t1: "Necessary cookies",
    s4d1: "The legal basis is the legitimate interest of the controller and the necessity for service provision, in accordance with Article 6.1.b) of Regulation (EU) 2016/679 (GDPR). These cookies do not require prior user consent.",
    s4t2: "Analytics and third-party service cookies",
    s4d2: "The legal basis is user consent, in accordance with Article 6.1.a) of the GDPR and Article 22.2 of Law 34/2002 (LSSI). Users may withdraw their consent at any time without affecting the lawfulness of processing carried out prior to withdrawal.",
    s5h: "5. Retention periods",
    s5c1: "Necessary (session)", s5p1: "Deleted when the browser is closed",
    s5c2: "Necessary (preferences)", s5p2: "12 months from creation",
    s5c3: "Analytics (Google Analytics)", s5p3: "Between 24 hours and 2 years, depending on the cookie",
    s5c4: "Third-party services", s5p4: "Variable; see each provider's policy",
    s6h: "6. International data transfers",
    s6p1: "Google LLC is established in the United States of America. Transfers of personal data to Google LLC are covered by the Standard Contractual Clauses approved by the European Commission and the EU-US Data Privacy Framework. For more information, please see the",
    s6link1: "Google Privacy Policy",
    s6p2: "Idealista.com Networks SL is established in Spain (European Union), so data processing by this provider does not constitute an international data transfer.",
    s7h: "7. How to manage or withdraw consent",
    s7intro: "Users can manage, modify or withdraw their consent at any time in two ways:",
    s7a: "a) Website cookie management panel",
    s7aDesc1: "By clicking the",
    s7aDesc2: "link in the footer, users can enable or disable each cookie category at any time.",
    s7b: "b) Browser settings",
    s7bDesc: "You can also manage, block or delete cookies installed on your device through your browser settings:",
    s7disclaimer: "Disabling certain cookies may affect the proper functioning of the website.",
    s7note: "Withdrawing consent does not affect the lawfulness of processing based on consent prior to withdrawal.",
    s8h: "8. Updates to this policy",
    s8p: "The controller reserves the right to update this Cookie Policy at any time, for example to reflect legislative changes or modifications to the website's services. We recommend reviewing this page periodically.",
    s9h: "9. Contact",
    s9p: "For any enquiries related to the use of cookies on this website, please contact the data controller:",
    backLegal: "Legal notice →", backPrivacy: "Privacy policy →", backHome: "← Back to home",
  },
  fr: {
    title: "Politique de Cookies",
    updated: "Dernière mise à jour : mai 2026",
    s1h: "1. Que sont les cookies ?",
    s1p: "Les cookies sont de petits fichiers texte que les sites web enregistrent sur l'appareil de l'utilisateur lorsqu'il les visite. Ils permettent au site de mémoriser des informations sur la visite : quelles pages ont été consultées, quelles préférences ont été indiquées ou si l'utilisateur était connecté. Les cookies ne peuvent pas exécuter de programmes ni transmettre de virus ; ce sont simplement des fichiers texte.",
    s2h: "2. Quels cookies utilisons-nous ?",
    s2intro: "Vous trouverez ci-dessous la liste complète des cookies utilisés sur thevilahome.com, regroupés par catégorie :",
    catNecessary: "Nécessaires",
    catNecessaryDesc: "Indispensables au fonctionnement de base du site web. Ils ne requièrent pas le consentement préalable de l'utilisateur.",
    colCookie: "Cookie", colProvider: "Fournisseur", colDuration: "Durée", colPurpose: "Finalité",
    colCategory: "Catégorie", colRetention: "Durée de conservation",
    fieldEmail: "Adresse électronique",
    idealistaPrivacy: "Politique de confidentialité d'Idealista",
    ownProvider: "Propre", session: "Session", months12: "12 mois",
    rowSession: "Gestion de la session de l'utilisateur",
    rowConsent: "Enregistrer les préférences cookies de l'utilisateur",
    rowPhp: "Fonctionnement technique du site web",
    catAnalytics: "Analytiques",
    catAnalyticsDesc: "Permettent de mesurer l'utilisation du site web via la collecte et l'analyse statistique du trafic. Gérés par Google LLC en tant que sous-traitant tiers. Activés uniquement si l'utilisateur donne son consentement.",
    years2: "2 ans", hours24: "24 heures",
    rowGa: "Distinguer les utilisateurs uniques",
    rowGaStar: "Maintenir l'état de session Analytics",
    rowGid: "Distinguer les utilisateurs au cours d'une session",
    moreInfo: "Plus d'informations :", googlePrivacy: "Politique de confidentialité de Google",
    catThirdParty: "Services tiers",
    catThirdPartyDesc: "Certaines pages intègrent des outils tiers : une carte Google Maps sur /contacto et le widget d'estimation Idealista sur /valoracion. Ces services peuvent installer leurs propres cookies.",
    variable: "Variable",
    rowMaps: "Afficher la carte interactive sur /contacto",
    rowWidget: "Widget d'estimation sur /valoracion",
    s3h: "3. À quoi servent les cookies ?",
    s3t1: "Cookies nécessaires",
    s3d1: "Assurent le fonctionnement technique du site web : ils maintiennent la session de l'utilisateur active pendant la navigation et enregistrent ses préférences de consentement aux cookies pour ne pas les lui redemander à chaque visite.",
    s3t2: "Cookies analytiques",
    s3d2: "Permettent d'obtenir des statistiques agrégées sur l'utilisation du site web : pages visitées, temps de présence, origine du trafic et comportement général des utilisateurs. Ces informations sont utilisées exclusivement pour améliorer les performances et le contenu du site.",
    s3t3: "Services tiers",
    s3d3: "Les services intégrés de Google Maps et Idealista fonctionnent de manière indépendante. Les cookies installés par ces services échappent au contrôle du responsable et sont régis exclusivement par les politiques de confidentialité de chaque fournisseur.",
    s4h: "4. Base légale du traitement",
    s4t1: "Cookies nécessaires",
    s4d1: "La base légale est l'intérêt légitime du responsable et la nécessité pour la prestation du service, conformément à l'article 6.1.b) du Règlement (UE) 2016/679 (RGPD). Ces cookies ne requièrent pas le consentement préalable de l'utilisateur.",
    s4t2: "Cookies analytiques et de services tiers",
    s4d2: "La base légale est le consentement de l'utilisateur, conformément à l'article 6.1.a) du RGPD et à l'article 22.2 de la loi 34/2002 (LSSI). L'utilisateur peut retirer son consentement à tout moment sans que cela n'affecte la licéité du traitement effectué antérieurement.",
    s5h: "5. Durées de conservation",
    s5c1: "Nécessaires (session)", s5p1: "Supprimés à la fermeture du navigateur",
    s5c2: "Nécessaires (préférences)", s5p2: "12 mois à compter de leur création",
    s5c3: "Analytiques (Google Analytics)", s5p3: "Entre 24 heures et 2 ans, selon le cookie",
    s5c4: "Services tiers", s5p4: "Variable ; voir la politique de chaque fournisseur",
    s6h: "6. Transferts internationaux de données",
    s6p1: "Google LLC est établie aux États-Unis d'Amérique. Les transferts de données personnelles vers Google LLC sont couverts par les Clauses Contractuelles Types approuvées par la Commission européenne et par le cadre EU-US Data Privacy Framework. Pour plus d'informations, veuillez consulter la",
    s6link1: "politique de confidentialité de Google",
    s6p2: "Idealista.com Networks SL est établie en Espagne (Union européenne), de sorte que le traitement des données effectué par ce fournisseur ne constitue pas un transfert international de données.",
    s7h: "7. Comment gérer ou retirer le consentement ?",
    s7intro: "L'utilisateur peut gérer, modifier ou retirer son consentement à tout moment de deux façons :",
    s7a: "a) Panneau de gestion des cookies du site",
    s7aDesc1: "En cliquant sur le lien",
    s7aDesc2: "situé dans le pied de page, l'utilisateur peut activer ou désactiver chaque catégorie de cookies à tout moment.",
    s7b: "b) Paramètres du navigateur",
    s7bDesc: "Vous pouvez également gérer, bloquer ou supprimer les cookies installés sur votre appareil via les paramètres de votre navigateur :",
    s7disclaimer: "La désactivation de certains cookies peut affecter le bon fonctionnement du site web.",
    s7note: "Le retrait du consentement ne portera pas atteinte à la licéité du traitement fondé sur le consentement antérieur à son retrait.",
    s8h: "8. Mise à jour de cette politique",
    s8p: "Le responsable se réserve le droit de mettre à jour cette Politique de Cookies à tout moment, par exemple pour l'adapter à des évolutions législatives ou à des modifications des services du site web. Nous vous recommandons de consulter cette page régulièrement.",
    s9h: "9. Contact",
    s9p: "Pour toute question relative à l'utilisation des cookies sur ce site web, veuillez contacter le responsable du traitement :",
    backLegal: "Mentions légales →", backPrivacy: "Politique de confidentialité →", backHome: "← Retour à l'accueil",
  },
};

export function getCookiesContent(lang: Lang): CookiesContent {
  return data[lang] ?? data.es;
}
